-- 코드를 입력하세요
SELECT USER.USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소,
CONCAT(SUBSTRING(TLNO, 1, 3), "-", SUBSTRING(TLNO, 4, 4), "-", SUBSTRING(TLNO, 8))  전화번호
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_USER USER ON BOARD.WRITER_ID = USER.USER_ID
GROUP BY USER.USER_ID
HAVING COUNT(USER.USER_ID) >= 3
ORDER BY USER.USER_ID DESC