-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(OS.SALES_DATE, "%Y") YEAR, 
    DATE_FORMAT(OS.SALES_DATE, "%m") MONTH, 
    UI.GENDER GENDER, 
    COUNT(DISTINCT UI.USER_ID) USERS
FROM ONLINE_SALE OS
JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER