-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM FOOD_ORDER FO
JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID 
WHERE "2022-05-01" <= FO.PRODUCE_DATE AND FO.PRODUCE_DATE < "2022-06-01"
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID