WITH RANKED AS (
    SELECT 
        MEMBER_ID,
        COUNT(*) AS CNT,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT 
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM RANKED R
JOIN REST_REVIEW RR ON RR.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE MP ON MP.MEMBER_ID = R.MEMBER_ID
WHERE R.RANKING = 1
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;
