-- 코드를 작성해주세요
SELECT O.ITEM_ID, O.ITEM_NAME, O.RARITY
FROM ITEM_TREE
JOIN ITEM_INFO P ON P.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
JOIN ITEM_INFO O ON O.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE P.RARITY = "RARE"
ORDER BY O.ITEM_ID DESC